"""init-db

Revision ID: 62196067116f
Revises: 
Create Date: 2022-12-07 13:09:25.314456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62196067116f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
